export async function getUserId(): Promise<string | null> {
  try {
    // Requires Stack Auth to be initialized via `npx @stackframe/init-stack . --no-browser`
    // and environment variables set. This file (`stack.ts`) is generated by the init command.
    // @ts-ignore
    const mod = await import("../stack");
    if (mod?.stackServerApp?.getUser) {
      const user = await mod.stackServerApp.getUser();
      return user?.id ?? null;
    }
  } catch {}
  return null;
}